[2025-08-28T13:40:47.443+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-28T13:40:47.486+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fitness_ml_pipeline.build_features manual__2025-08-28T13:40:46.583668+00:00 [queued]>
[2025-08-28T13:40:47.489+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fitness_ml_pipeline.build_features manual__2025-08-28T13:40:46.583668+00:00 [queued]>
[2025-08-28T13:40:47.489+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-28T13:40:47.497+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): build_features> on 2025-08-28 13:40:46.583668+00:00
[2025-08-28T13:40:47.510+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fitness_ml_pipeline', 'build_features', 'manual__2025-08-28T13:40:46.583668+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/fitness_pipeline_dag.py', '--cfg-path', '/tmp/tmputnjfaxi']
[2025-08-28T13:40:47.513+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask build_features
[2025-08-28T13:40:47.517+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=423) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-28T13:40:47.517+0000] {standard_task_runner.py:63} INFO - Started process 424 to run task
[2025-08-28T13:40:47.553+0000] {task_command.py:426} INFO - Running <TaskInstance: fitness_ml_pipeline.build_features manual__2025-08-28T13:40:46.583668+00:00 [running]> on host b9a4a7344080
[2025-08-28T13:40:47.613+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fitness_ml_pipeline' AIRFLOW_CTX_TASK_ID='build_features' AIRFLOW_CTX_EXECUTION_DATE='2025-08-28T13:40:46.583668+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-28T13:40:46.583668+00:00'
[2025-08-28T13:40:47.615+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-28T13:40:47.685+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2025-08-28T13:40:47.686+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.sql.shuffle.partitions=8 --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.cores=1 --jars /opt/spark/connectors/hadoop-aws-3.3.4.jar,/opt/spark/connectors/aws-java-sdk-bundle-1.12.262.jar --name arrow-spark --verbose /opt/spark/apps/build_features.py
[2025-08-28T13:40:47.757+0000] {spark_submit.py:491} INFO - /opt/spark/bin/spark-class: line 71: /usr/lib/jvm/java-17-openjdk-amd64/bin/java: No such file or directory
[2025-08-28T13:40:47.759+0000] {spark_submit.py:491} INFO - /opt/spark/bin/spark-class: line 97: CMD: bad array subscript
[2025-08-28T13:40:47.775+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-28T13:40:47.786+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.sql.shuffle.partitions=8 --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.cores=1 --jars /opt/spark/connectors/hadoop-aws-3.3.4.jar,/opt/spark/connectors/aws-java-sdk-bundle-1.12.262.jar --name arrow-spark --verbose /opt/spark/apps/build_features.py. Error code is: 1.
[2025-08-28T13:40:47.796+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fitness_ml_pipeline, task_id=build_features, run_id=manual__2025-08-28T13:40:46.583668+00:00, execution_date=20250828T134046, start_date=20250828T134047, end_date=20250828T134047
[2025-08-28T13:40:47.803+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task build_features (Cannot execute: spark-submit --master spark://spark-master:7077 --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 --conf spark.hadoop.fs.s3a.access.key=minioadmin --conf spark.hadoop.fs.s3a.secret.key=****** --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem --conf spark.sql.shuffle.partitions=8 --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.executor.cores=1 --jars /opt/spark/connectors/hadoop-aws-3.3.4.jar,/opt/spark/connectors/aws-java-sdk-bundle-1.12.262.jar --name arrow-spark --verbose /opt/spark/apps/build_features.py. Error code is: 1.; 424)
[2025-08-28T13:40:47.822+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-28T13:40:47.835+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-28T13:40:47.837+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
